### ISSUE TITLE
Can't change chain - Signed into CB wallet but wallet app closed

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/fractal-interface#1777] opened 2024-05-13 13:03 UTC
see description of issue in this chain 

 I've managed to reproduce @azadikoff 's first issue [here](https://decentdao.slack.com/archives/C06QZTUTKRC/p1715359200267879?thread_ts=1715353726.616559&cid=C06QZTUTKRC)  raised around not being able to switch to sepolia.

In short for CBWallet there's a weird edge case. 

If you were/are signed into our app on a CBwallet in a prior session... BUT, your CB wallet app is now closed. Then the homepage WILL NOT change chain in the top right, no matter how many times you click it. 

Note, as soon as you open the CBwallet app, the chain will change as expected. if you have never connected to CB wallet, this also isn't an issue. Finally, this doesn't seem to be an issue on metamask which requests the user manually approve any chain switches. This implies, its something to do with CB wallet letting a user switch chain on a connected app without a manual approval on their app

**Comment by adamgall** [comment] 2024-05-16 23:04
@tomstuart123 i'm going to push back on this, say it's not a bug or issue or even really unexpected or unintended behavior.

on iOS i connected to the webapp through Coinbase Wallet.

- with coinbase wallet app open, i was able to easily and fluidly switch between networks using the webapp.
- with coinbase wallet app backgrounded, i was able to easily and fluidly switch between networks using the webapp. notably, i was receiving notifications on my phone from CBWallet stating that the network was changing, when i switched networks in webapp.
- with coinbase wallet app killed, switching networks in the webapp did not work. this doesn't surprise me, because it's the wallet that needs to provide the webapp with chain information when a wallet is connected. i don't think it's unreasonable for the CBWallet to not be able to gracefully end the connection with the webapp when it's been killed by the system/user.
  - BUT, importantly, when i was attempting to switch networks in the webapp, i was receiving notifications on my phone stating that a new "change network" request is happening. when i tap the notification, the CBWallet app opens, and the chain switches as expected.

Is there any other behavior that you think should be happening here instead? @azadikoff @tomstuart123

**Comment by tomstuart123** [comment] 2024-05-17 12:01
Yep I had the same behaviour except I wasn't getting the notifications you mentioned at the end. Hopefully other users get them. @azadikoff recommend we call this out specifically in the bug bash to see if people get the same

@adamgall tldr - this is an edge scenario when compared to the scenarios. Sounds like its expected behaviour and isn't really 'within our system' to try and improve on if we wanted to. Happy to leave for now

**Comment by adamgall** [comment] 2024-05-20 20:29
Would like to close this issue. @tomstuart123 thoughts?

**Comment by tomstuart123** [comment] 2024-05-21 12:39
closed for now. We can reopen specific issues based on what parker and nicolas face specifically on pre-setting up their 'Demo DAO' as they will be the demo people

**Closed** 2024-05-21 13:20 UTC
Labels: re-skin
