### ISSUE TITLE
Can't return home from logo in top left of nav

### ISSUE THREAD

**Issue by nicolaus-sherrill** [decentdao/fractal-interface#1750] opened 2024-05-09 17:30 UTC
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYmVlNWZhYTA4OWIwMDA5ODJhODg4IiwiaWQiOiI4MDBhOWIwNS0yNTdiLTRiMjAtODcyZi0yZjZhNmFmNDI1MzUifQ==)

### Description of issue
Can't return home from logo in top left of nav. This is leaving me stuck in the current DAO I am viewing unless I navigate back with my browser.

### Expected result
I click the logo to return to the app home.

### Actual result
Logo is not clickable.

```
Path:      /
Browser:   Firefox 125.0 on Mac OS 10.15
Viewport:  1680 x 910 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2F&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=125.0&resolution=1680x910&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1578](https://deploy-preview-1578.app.dev.fractalframework.xyz/)

**Comment by adamgall** [comment] 2024-05-10 14:30
@nicolaus-sherrill that logo is most definitely clickable (and navigates back to fractal home) on my machine!

can you reproduce this right now? if so, what browser are you on?

**Comment by nicolaus-sherrill** [comment] 2024-05-10 15:11
@adamgall I'm on Firefox, and the logo is still not clickable.

**Comment by adamgall** [comment] 2024-05-10 15:16
@nicolaus-sherrill yep, this logo isn't clickable on Firefox. 

@decentdao/engineers , looks like the sidebar element is stretching to the top of the page on Firefox, covering the logo.

**Comment by adamgall** [comment] 2024-05-10 17:57
Closed via https://github.com/decentdao/fractal-interface/pull/1758

**Closed by adamgall** 2024-05-10 17:57 UTC
Labels: re-skin
